version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    container_name: Backend
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5000:5000"
    container_name: Frontend
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: calorie-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: PostgreSQL

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: name@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5555:80"
    container_name: PGadmin4
    depends_on:
      - db
